#!/usr/bin/env bash
set -Eeuo pipefail
export PATH="/usr/lib/postgresql/18/bin:$PATH"
SOURCE_ADMIN_URL='postgresql://postgres:postgres@127.0.0.1:55432/postgres'
DESTINATION_ADMIN_URL='postgresql://postgres:postgres@127.0.0.1:55433/postgres'
SOURCE_URL='postgresql://postgres:postgres@127.0.0.1:55432/cycle_d_source'
DESTINATION_URL='postgresql://postgres:postgres@127.0.0.1:55433/cycle_d_destination'
psql "$SOURCE_ADMIN_URL" -v ON_ERROR_STOP=1 -c 'create database cycle_d_source;'
psql "$DESTINATION_ADMIN_URL" -v ON_ERROR_STOP=1 -c 'create database cycle_d_destination;'
psql "$SOURCE_URL" -v ON_ERROR_STOP=1 <<'SQL'
create table public.receipts (
  id bigint generated by default as identity primary key,
  bill_no text not null
);
insert into public.receipts (bill_no) values ('SOURCE-1'), ('SOURCE-2');
SQL
psql "$DESTINATION_URL" -v ON_ERROR_STOP=1 <<'SQL'
create table public.receipts (
  id bigint primary key,
  bill_no text not null
);
insert into public.receipts (id, bill_no) values (1, 'SOURCE-1');
SQL
source_identity_before="$(psql "$SOURCE_URL" -Atc "select attidentity from pg_attribute where attrelid='public.receipts'::regclass and attname='id';")"
destination_identity_before="$(psql "$DESTINATION_URL" -Atc "select attidentity from pg_attribute where attrelid='public.receipts'::regclass and attname='id';")"
set +e
runtime_output="$(SOURCE_DATABASE_URL="$SOURCE_URL" DESTINATION_DATABASE_URL="$DESTINATION_URL" bash scripts/neon-sync/append-sync.sh 2>&1)"
sync_exit=$?
set -e
printf '%s\n' "$runtime_output"
destination_identity_after="$(psql "$DESTINATION_URL" -Atc "select attidentity from pg_attribute where attrelid='public.receipts'::regclass and attname='id';")"
destination_row_2="$(psql "$DESTINATION_URL" -At -F '|' -c "select id,bill_no from public.receipts where bill_no='SOURCE-2';")"
set +e
probe_output="$(psql "$DESTINATION_URL" -v ON_ERROR_STOP=1 -At -F '|' -c "insert into public.receipts (bill_no) values ('DEST-AUTO'); select id,bill_no from public.receipts where bill_no='DEST-AUTO';" 2>&1)"
probe_exit=$?
set -e
printf 'NEON_IDENTITY_SYNC_EXIT=%s\n' "$sync_exit"
printf 'NEON_IDENTITY_SOURCE_BEFORE=%s\n' "$source_identity_before"
printf 'NEON_IDENTITY_DESTINATION_BEFORE=%s\n' "$destination_identity_before"
printf 'NEON_IDENTITY_DESTINATION_AFTER=%s\n' "$destination_identity_after"
printf 'NEON_IDENTITY_APPENDED_SOURCE_ROW=%s\n' "$destination_row_2"
printf 'NEON_IDENTITY_PROBE_EXIT=%s\n' "$probe_exit"
printf 'NEON_IDENTITY_PROBE_OUTPUT=%s\n' "$probe_output"
test "$source_identity_before" = 'd'
test -z "$destination_identity_before"
if [[ "$sync_exit" -ne 0 ]]; then
  if grep -Eiq 'identity|receipts.*id' <<<"$runtime_output"; then
    echo 'NEON_IDENTITY_COLUMN_DRIFT_DETECTED=true'
    exit 0
  fi
  echo 'NEON_IDENTITY_COLUMN_DRIFT_DETECTED=unverified' >&2
  exit 1
fi
if [[ "$destination_identity_after" = 'd' \
      && "$destination_row_2" = '2|SOURCE-2' \
      && "$probe_exit" -eq 0 \
      && "$probe_output" == *'DEST-AUTO'* \
      && "$runtime_output" == *'Append sync and verification completed successfully for default.'* ]]; then
  echo 'NEON_IDENTITY_COLUMN_DRIFT_DETECTED=true'
  exit 0
fi
echo 'NEON_IDENTITY_COLUMN_DRIFT_DETECTED=false' >&2
echo 'Production reported successful synchronization without preserving source identity semantics on the writable destination.' >&2
exit 1
