#!/usr/bin/env bash
set -Eeuo pipefail

if [[ -z "${SOURCE_DATABASE_URL:-}" ]]; then
  echo "SOURCE_DATABASE_URL secret is missing." >&2
  exit 1
fi

if [[ -z "${DESTINATION_DATABASE_URL:-}" ]]; then
  echo "DESTINATION_DATABASE_URL secret is missing." >&2
  exit 1
fi

validate_database_url() {
  local name="$1"
  local value="$2"

  if [[ "$value" == psql* ]]; then
    echo "$name must be only the postgresql:// connection URL, not a full psql command." >&2
    exit 2
  fi

  if [[ "$value" == *\\_* ]] || [[ "$value" == *\\@* ]]; then
    echo "$name contains backslash escapes. Paste the raw Neon URL without Markdown escaping." >&2
    exit 2
  fi

  if [[ "$value" != postgresql://* && "$value" != postgres://* ]]; then
    echo "$name must start with postgresql:// or postgres://." >&2
    exit 2
  fi
}

validate_database_url "SOURCE_DATABASE_URL" "$SOURCE_DATABASE_URL"
validate_database_url "DESTINATION_DATABASE_URL" "$DESTINATION_DATABASE_URL"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

schema_file="$workdir/source-schema.sql"
copy_file="$workdir/source-data.sql"
source_columns="$workdir/source-columns.tsv"
destination_columns="$workdir/destination-columns.tsv"
missing_columns_sql="$workdir/add-missing-columns.sql"
excluded_tables="${EXCLUDED_TABLES:-}"

echo "Checking source connection..."
psql "$SOURCE_DATABASE_URL" -v ON_ERROR_STOP=1 -Atc "select current_database();"

echo "Checking destination connection..."
psql "$DESTINATION_DATABASE_URL" -v ON_ERROR_STOP=1 -Atc "select current_database();"

echo "Dumping source schema..."
pg_dump \
  --schema-only \
  --no-owner \
  --no-privileges \
  "$SOURCE_DATABASE_URL" \
  > "$schema_file"

echo "Creating any missing schema objects on destination..."
psql "$DESTINATION_DATABASE_URL" -v ON_ERROR_STOP=0 -f "$schema_file"

column_query="
select
  n.nspname as table_schema,
  c.relname as table_name,
  a.attname as column_name,
  a.attnum as ordinal_position,
  pg_catalog.format_type(a.atttypid, a.atttypmod) as column_type,
  pg_get_expr(ad.adbin, ad.adrelid) as column_default,
  a.attidentity as identity_kind,
  a.attgenerated as generated_kind
from pg_catalog.pg_attribute a
join pg_catalog.pg_class c on c.oid = a.attrelid
join pg_catalog.pg_namespace n on n.oid = c.relnamespace
left join pg_catalog.pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
where a.attnum > 0
  and not a.attisdropped
  and c.relkind in ('r', 'p')
  and n.nspname not in ('pg_catalog', 'information_schema')
order by n.nspname, c.relname, a.attnum;
"

psql "$SOURCE_DATABASE_URL" -v ON_ERROR_STOP=1 -At -F $'\t' -c "$column_query" > "$source_columns"
psql "$DESTINATION_DATABASE_URL" -v ON_ERROR_STOP=1 -At -F $'\t' -c "$column_query" > "$destination_columns"

node - "$source_columns" "$destination_columns" "$missing_columns_sql" <<'NODE'
const fs = require('fs');

const [sourcePath, destinationPath, outputPath] = process.argv.slice(2);

function readRows(path) {
  const text = fs.readFileSync(path, 'utf8').trim();
  if (!text) return [];
  return text.split(/\r?\n/).map((line) => {
    const [
      table_schema,
      table_name,
      column_name,
      ordinal_position,
      column_type,
      column_default,
      identity_kind,
      generated_kind,
    ] = line.split('\t');
    return {
      table_schema,
      table_name,
      column_name,
      ordinal_position: Number(ordinal_position),
      column_type,
      column_default,
      identity_kind,
      generated_kind,
    };
  });
}

function ident(value) {
  return `"${String(value).replace(/"/g, '""')}"`;
}

const sourceRows = readRows(sourcePath);
const destinationRows = readRows(destinationPath);
const destinationKeys = new Set(
  destinationRows.map((row) => `${row.table_schema}.${row.table_name}.${row.column_name}`),
);

const statements = [];
for (const row of sourceRows) {
  const key = `${row.table_schema}.${row.table_name}.${row.column_name}`;
  if (destinationKeys.has(key)) continue;

  const parts = [
    `alter table ${ident(row.table_schema)}.${ident(row.table_name)}`,
    `add column if not exists ${ident(row.column_name)}`,
    row.column_type,
  ];

  if (row.identity_kind === 'a') {
    parts.push('generated always as identity');
  } else if (row.identity_kind === 'd') {
    parts.push('generated by default as identity');
  } else if (row.generated_kind) {
    continue;
  } else if (row.column_default) {
    parts.push(`default ${row.column_default}`);
  }

  statements.push(`${parts.join(' ')};`);
}

fs.writeFileSync(outputPath, statements.join('\n') + (statements.length ? '\n' : ''));
console.log(`Missing columns to add: ${statements.length}`);
NODE

if [[ -s "$missing_columns_sql" ]]; then
  echo "Adding missing destination columns..."
  psql "$DESTINATION_DATABASE_URL" -v ON_ERROR_STOP=1 -f "$missing_columns_sql"
else
  echo "No missing destination columns found."
fi

exclude_args=()
if [[ -n "$excluded_tables" ]]; then
  IFS=',' read -ra excluded <<< "$excluded_tables"
  for table_name in "${excluded[@]}"; do
    trimmed="$(echo "$table_name" | xargs)"
    if [[ -n "$trimmed" ]]; then
      exclude_args+=(--exclude-table-data="$trimmed")
    fi
  done
fi

echo "Dumping source data as insert statements..."
pg_dump \
  --data-only \
  --inserts \
  --on-conflict-do-nothing \
  --no-owner \
  --no-privileges \
  "${exclude_args[@]}" \
  "$SOURCE_DATABASE_URL" \
  > "$copy_file"

echo "Appending data into destination..."
psql "$DESTINATION_DATABASE_URL" -v ON_ERROR_STOP=1 -f "$copy_file"

echo "Append sync completed successfully."
